In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np
import csv
from sklearn.preprocessing import LabelEncoder
import statistics as stts

In [ ]:

lector = csv.reader(open("baseMomentos.csv","r"))
lectorTest = csv.reader(open("TestMomentos.csv","r"))
base = np.array([[[float(dato) for dato in linea[:-1]]] for linea in lector])
baseTest = np.array([[[float(dato) for dato in linea[:-1]]] for linea in lectorTest])

In [ ]:
print(base.shape)

(853, 1, 3)


In [ ]:

#obtener las etiquetas
lector = csv.reader(open("baseMomentos.csv","r"))
lectorTest = csv.reader(open("TestMomentos.csv","r"))
etiquetas= [linea[-1] for linea in lector]
etiquetasTest= [linea[-1] for linea in lectorTest]
clases = set(etiquetas)

print(base)
print(etiquetas)
print(clases)

[[[9.52698019e-04 7.07158116e-10 2.95306659e-13]]

 [[9.04713114e-04 1.48740305e-11 1.35792330e-13]]

 [[9.85600339e-04 4.73575179e-10 5.11457536e-12]]

 ...

 [[1.44373262e-03 3.00629536e-08 4.04684258e-11]]

 [[8.64438214e-04 8.91814729e-10 4.65550620e-13]]

 [[1.03392428e-03 4.67129016e-09 7.02201808e-12]]]
['botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'botella', 'bote

In [ ]:
label_encoder = LabelEncoder()

# Ajustar el codificador a los datos de entrada y obtener las etiquetas codificadas
etiquetas_codificadas = label_encoder.fit_transform(etiquetas)
etiquetas_codificadasTest = label_encoder.fit_transform(etiquetasTest)
# Convertir las etiquetas codificadas en un arreglo de números
arreglo_numeros = np.array(etiquetas_codificadas)
arreglo_numerosTest = np.array(etiquetas_codificadasTest)
# print(arreglo_numeros)

In [ ]:

modelo = Sequential()
modelo.add(tf.keras.Input(shape=(1,3)))
modelo.add(Dense(32,activation='relu'))
modelo.add(Dense(32,activation='relu'))
modelo.add(Dense(2,activation='softmax'))

modelo.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])


In [ ]:
# Resumen del modelo
modelo.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_18 (Dense)            (None, 1, 32)             128       
                                                                 
 dense_19 (Dense)            (None, 1, 32)             1056      
                                                                 
 dense_20 (Dense)            (None, 1, 2)              66        
                                                                 
Total params: 1,250
Trainable params: 1,250
Non-trainable params: 0
_________________________________________________________________


In [ ]:

modelo.fit(base,arreglo_numeros,batch_size=4,epochs=10,verbose=1)


Epoch 1/10
214/214 [==============================] - 1s 2ms/step - loss: 0.6900 - accuracy: 0.5494
Epoch 2/10
214/214 [==============================] - 0s 2ms/step - loss: 0.6885 - accuracy: 0.5494
Epoch 3/10
214/214 [==============================] - 0s 2ms/step - loss: 0.6891 - accuracy: 0.5503
Epoch 4/10
214/214 [==============================] - 0s 2ms/step - loss: 0.6889 - accuracy: 0.5503
Epoch 5/10
214/214 [==============================] - 0s 2ms/step - loss: 0.6894 - accuracy: 0.5503
Epoch 6/10
214/214 [==============================] - 0s 2ms/step - loss: 0.6892 - accuracy: 0.5494
Epoch 7/10
214/214 [==============================] - 0s 2ms/step - loss: 0.6890 - accuracy: 0.5494
Epoch 8/10
214/214 [==============================] - 1s 3ms/step - loss: 0.6887 - accuracy: 0.5503
Epoch 9/10
214/214 [==============================] - 1s 3ms/step - loss: 0.6886 - accuracy: 0.5503
Epoch 10/10
214/214 [==============================] - 0s 2ms/step - loss: 0.6890 - accuracy: 0.5494

In [ ]:
def clases(arreglo):
    if np.argmax(arreglo)==0:
      print("botella")
    if np.argmax(arreglo)==1:
      print("no botella")

In [ ]:

score = modelo.evaluate(baseTest,arreglo_numerosTest,verbose=1)
print('perdida en prueba: ', score[0])
print('precision en prueba: ', score[1])


1/1 [==============================] - 0s 215ms/step - loss: 0.7053 - accuracy: 0.4762
perdida en prueba:  0.7053112983703613
precision en prueba:  0.4761904776096344


In [ ]:
entrada_test = [[[0.0008950785159353671,3.327421725324484e-11,1.5224188482300927e-13]]]
prediccion = modelo.predict(entrada_test)
porcentajeParecido = prediccion[0][0]
clases(prediccion[0])

1/1 [==============================] - 0s 159ms/step
botella


In [ ]:
entrada = [[[0.0012545370989574022,4.334490903497911e-09,2.8873958144269634e-11]]]
prediccion = modelo.predict(entrada)
porcentajeParecido = prediccion[0][0]
print(f'porcentaje de botella: {porcentajeParecido}')
clases(prediccion[0])

1/1 [==============================] - 0s 43ms/step
porcentaje de botella: [0.55750996 0.4424901 ]
botella


In [ ]:
modelo.save("modelo.h5")

# Guardar solo los pesos del modelo
modelo.save_weights("pesos.h5")